language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "stable"
before_install:
  - npm install -g npm@next
sudo: false
after_success:
  - npm install coveralls
  - nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
